export const application = {
    fileUpload_success:"File uploaded successfully!",
    multipleSelectNotFound:"No results found, please try again.",
    notFound:"Not found",
    totalHourExceedInTimesheet:"Total hours should not exceed 24.",
    canNotEnterfutureDateTimesheet:"You can't enter timesheet for future date.",
    timeshhetActivitySelection:"Please select an activity.",
    timesheetHourShouldNotZero:"Hour should not be 0 or greater than 24.",
    timesheetDescription:"Please enter description.",
    timesheetLocation:"Please select a location.",
    previousMonthTimesheetEntry:"You cannot enter previous month's Timesheet.",
    noDataToSaveForTimesheet:"No data to save.",
    notEnteredCompanyName:"Please enter company name.",
    notEnteredPractice:"Please select practice",
    fillEmpType:"Please fill employee type.",
    fillEmpAddress:"Please fill address.",
    fillMandatoryFields:"Please fill all mandatory fields (marked in *).",
    fillToolInProject:"Please fill Tool Used.",
    projectApprovalRemarks:"Approval date exceeds project creation date by 5 days \n\nRemarks is mandatory.",
    forgetPassOtp:"OTP has sent successfully on your emailID.",
    forgetPassBlankEmailId:"Email ID can not be left blank.",
    loginValidEmpId:"Please enter a valid employee ID.",
    loginEnterEmpId:"Please enter your employee ID.",
    empCodeNotExistInLogin:"Employee ID doesn't exist !",
    correctPasswordInLogin:"Please enter correct password !",
    enterPass:"Please enter password!",
    enterEmpId:"Please enter employee ID!",
    logoutAreSureMsg:"Are you sure?",
    logoutDoYouRealyMsg:"Do you really want to logout.",
    projectAssignedSucess:"Project Assigned Successfully.",
    projectAssignStEdDate:"Please select project start date and end date.",
    selectEmpAndProject:"Please select employee and project.",
    fileUpload_failed:"File upload failed. please try again!",
    session_timeout: "Session Logged out. Please login again!",
    application_name: "Payment Tracking Application"
};

export const message = {
    success : "Success",
    customerCreatedSuccess: "Customer Created Successfully",
    customerCreationError: "Unable to Create Customer. Please try again later!",
    customerEditedSuccess: "Customer Updated Successfully",
    customerEditError: "Unable to Update Customer. Please try again later!",
    projectCreatedSuccess: "Project Created Successfully",
    projectCreationError: "Unable to Create Project. Please try again later!",
    projectEditedSuccess: "Project Updated Successfully",
    projectEditError: "Unable to Update Project. Please try again later!",
    superPoCreatedSuccess: "Purchase Order Created Successfully",
    superPoCreationError: "Unable to Create Purchase Order. Please try again later!",
    superPoEditedSuccess: "Purchase Order Updated Successfully",
    superPoEditError: "Unable to Update Purchase Order. Please try again later!",
    warning : "Warning",
    error : "Error",
    sessionTimeout: "Session Time out. Please login again",
    invalidUser: "Invalid Username / Password",
    uploadSuccess: "Uploaded Successfully",
    uploadFailed: "Upload Failed. Please try again later!",
    changePassword:"Successfully Password Changed. Please relogin again ",
    changePasswordFailed:"Unable to change password. Please try again later",
    billingIndentUpdatedSuccess:"Successfully updated Billing Indent ",
    billingIndentUpdatedFailed:"Unable to update Billing Indent ",
    billingReviewUpdatedSuccess:"Successfully updated Reviews ",
    billingReviewUpdatedFailed:"Unable to update Reviews. Please try again later ",
    paymentTrackSuccess:"Updated Payment Details Successfully",
    paymentTrackFailed:"Error in updating Payment Details. Please try again later",
    billingResubmitUpdatedSuccess:"Successfully Resubmitted ",
    billingResubmitUpdatedFailed:"Unable to Resubmit. Please try again later ",
    posplit_source_target_same : "Source Practice and Target Practice cannot be the same",
}